### ISSUE TITLE
Carga de renglones en el Punto de Venta

### ISSUE THREAD

**Issue by belluccifranco** [belluccifranco/sic#15]
Se debe poder seguir cargando renglones en el Punto de Venta aunque pase la cantidad limite de renglones para una página. Luego al cerrar la venta, el sistema debe generar tantas facturas como páginas cargadas automaticamente.

**Comment by k31kur0n0** [comment]
Considerar ambos lugares desde donde se puede dar de alta una Factura de Venta

**Comment by belluccifranco** [comment]
No se arreglará esto ya que nos dimos cuenta que afectará negativamente la usabilidad al perder la cuenta de las facturas y sus totales.
