### ISSUE TITLE
Eliminar varios productos a la vez en Factura Venta

### ISSUE THREAD

**Issue by belluccifranco** [belluccifranco/sic#16]
El sistema debe permitir eliminar varios renglones a la vez cuando se esta dando de alta una factura de venta.

Actualmente solo permite eliminar de a uno.

**Comment by belluccifranco** [comment]
Considerar tanto el Punto de Venta, como el alta de Facturas en Administracion

**Comment by k31kur0n0** [comment]
Copiar la funcionalidad de Stock ---> Productos

**Comment by k31kur0n0** [comment]
Solucionado.
