### ISSUE TITLE
Test de Integracion: Compra con Factura A

### ISSUE THREAD

**Issue by belluccifranco** [belluccifranco/sic#238]
Dos productos dados de alta, uno con el 21 de IVA y el otro con 10.5 de IVA.
Dar de alta una Factura de compra A con ambos productos.
Verificar el stock de ambos productos.
Agregar un pago parcial. Vefiricar estado de la factura.
Agregar un pago total. Verificar el estado de la factura.

**Comment by k31kur0n0** [comment]
Dos productos dados de alta, uno con el 21 de IVA y el otro con 10.5 de IVA.
Dar de alta una Factura de compra A con ambos producto.
Verificar el stock de ambos productos.

**Comment by belluccifranco** [comment]
https://spring.io/blog/2016/04/15/testing-improvements-in-spring-boot-1-4
