### ISSUE TITLE
Test de Integracion: Venta con Factura B

### ISSUE THREAD

**Issue by belluccifranco** [belluccifranco/sic#239]
Dar de alta dos Productos, con 21 y 10.5 de IVA respectivamente.
Dar de alta una Factura de Venta B.
Verificar el stock.

**Comment by k31kur0n0** [comment]
Dar de alta dos Productos, con 21 y 10.5 de IVA respectivamente.
Dar de alta una Factura de Venta A.
Verificar el stock.

**Comment by belluccifranco** [comment]
https://spring.io/blog/2016/04/15/testing-improvements-in-spring-boot-1-4
