### ISSUE TITLE
Permitir marcar todos los checkbox a la vez. 

### ISSUE THREAD

**Issue by k31kur0n0** [belluccifranco/sic#24]
Los checkbox en Punto de Venta y en formFacturaVenta deben poder marcarse todos a la vez.

**Comment by belluccifranco** [comment]
Comportamiento deseado:
Al clickear por primera vez, debe marcar todos los check, al clickear de nuevo, debe desmarcar todos indefectiblemente.

**Comment by belluccifranco** [comment]
Solucionado
