### ISSUE TITLE
Test de Integracion: Facturacion de un Pedido

### ISSUE THREAD

**Issue by k31kur0n0** [belluccifranco/sic#246]
Dar de alta dos productos, 21 y 10.5 de IVA.
Dar de alta un pedido.
Facturar parcialmente el pedido con una A, verificar la factura, el estado del pedido y el stock.
Factura totalmente el pedido con una B, verificar el estado, ya factura y el stock.

**Comment by belluccifranco** [comment]
https://spring.io/blog/2016/04/15/testing-improvements-in-spring-boot-1-4
