### ISSUE TITLE
Cantidad minima de compra

### ISSUE THREAD

**Issue by belluccifranco** [belluccifranco/sic#272]
Agregar un nuevo atributo a Producto para determinar la cantidad minima que se puede vender.
Podria ir en la seccion de "Propiedades" en DetalleProductoGUI.
Este atributo debe mostrarse en el reporte de lista de precios

**Comment by k31kur0n0** [comment]
La cantidad mínima debe ser un valor informativo, no bloqueante de la operación de venta.
