### ISSUE TITLE
Problema con los nombres de tablas en linux

### ISSUE THREAD

**Issue by belluccifranco** [belluccifranco/sic#28]
Al parecer los nombres de tablas en Linux no son los mismos que en Windows y la app no las encuentra.
Una posible solucion podría ser usar la anotación @Table para forzar el nombre de la tabla.
Ej.:

@Entity
@Table(name = "cliente")

**Comment by delcampoAriel** [comment]
Al exportar el script Structure_SIC_v1.x.sql desde entornos Windows genera el nombre de las tablas de la BD en minúsculas. 
Como primera instancia para solucionar la importación y la creación de la BD en entornos linux se debe compilar el proyecto con la sigiente propiedad descomentada del siguiente archivo de configuración:

persistence.xml
<property name="hibernate.hbm2ddl.auto" value="create"/>

Luego de compilar volver a comentar dicha línea así se puede mantener la persistencia de los datos en la BD.

**Comment by belluccifranco** [comment]
Segun la documentación de MySQL, al instalarse en Linux, las tablas son case sensitive, mientras que en Windows no.
El fix va consistir en lograr que las tablas tengan el mismo nombre en todos los Sistemas Operativos.

**Comment by belluccifranco** [comment]
Solucionado
