### ISSUE TITLE
Nueva app sic-ecom

### ISSUE THREAD

**Issue by belluccifranco** [belluccifranco/sic#286]
Crear una nueva app en el raiz del repository, con el nombre "sic-ecom".
Usar el CLI de angular

**Comment by marcecruz25** [comment]
Tener instalado npm y node.
Instalar angular/cli : 
  - npm install -g @angular/cli
Creamos el proyecto:
  - ng new sic-ecom
Instalamos el RC.1:
  - sudo npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@next --save (Referencia: https://github.com/angular/angular/blob/master/CHANGELOG.md).
Instalamos el typescript:
  - sudo npm install typescript@2.2.1 --save.
Levantar la app:
  - ng serve
