### ISSUE TITLE
Unificar punto de venta y nueva Factura de venta.

### ISSUE THREAD

**Issue by k31kur0n0** [belluccifranco/sic#29]
La ventana de Punto de venta puede replicar comportamiento o ser la misma para generar una nueva factura como administrador.

**Comment by belluccifranco** [comment]
Hay que tener en cuenta las busquedas de Productos, no son las mismas. En la parte de Administracion tiene mas opciones.

**Comment by belluccifranco** [comment]
Por favor, testear que todo ande bien y luego cerrar este ticket.
