### ISSUE TITLE
Hotfixes para la 2.3

### ISSUE THREAD

**Issue by k31kur0n0** [belluccifranco/sic#291]
- Solucionar bug, desde pedidos no se pueden generar pedidos.
- Colocar icono en la ventana de nuevo Gasto.
- En la vista de Pedidos eliminar del label "(Vendedor)"
- Eliminar la posibilidad de ingresar un descuento/recargo negativo.

**Comment by belluccifranco** [comment]
- Total Caja y Total General debe actualizarse cada vez que se consulta una forma de pago. Consideral la resiliencia.
- Verificar el caso en que una caja no actualizada consulte por una forma de pago sin movimientos.
- En Administrar cajas solo listar los usuarios administradores.
- El "hasta" de las cajas debe ser como maximo 23:59:59 del mismo día, al cierre automático.
- Eliminar la posibilidad de ingresar un descuento/recargo negativo.
