### ISSUE TITLE
Arreglos en Caja

### ISSUE THREAD

**Issue by belluccifranco** [belluccifranco/sic#296]
- Total Caja y Total General deben actualizarse cada vez que se consulta una forma de pago. Considerar la resiliencia.
- Verificar el caso en que una caja no actualizada consulte por una forma de pago sin movimientos.
- En Administrar Cajas solo listar los usuarios administradores. Validar que el usuario que abre la caja posea el Rol Administrador.
- El "hasta" de las cajas debe ser como maximo 23:59:59 del mismo día, al cierre automático.
- Si la caja del día es eliminada, debe poderse abrir nuevamente la del día.

**Comment by k31kur0n0** [comment]
- Eliminar getCajaPorNroYEmpresa
- Eliminar concepto de ultima caja
- Eliminar codigo caja reporte en service
- La CajaDebe cerrar con el total que afecta caja únicamente
 - Los services de Pago y Gasto, deben recibir como params: idEmpresa, fechaDesde, fechaHasta y formaDePago
- Aplicar Hook Desing Pattern y agregar los siguientes atributos al model de Caja. 


    @Transient
    private List<Pago> pagos;
    
    @Transient
    private List<Gasto> gastos;
    
    @Transient
    private double totalAfectaCaja;
            
    @Transient
    private double totalGeneral;
