### ISSUE TITLE
Factura Electronica: SIC-Ops

### ISSUE THREAD

**Issue by belluccifranco** [belluccifranco/sic#311]
- Agregar CAE y Vencimiento CAE al reporte de Factura
- En la vista de Config del Sistema permitir dar de alta el certificado afip y guardarlo en la DB
- Validaciones para nuevos atributos: ej: nro punto de venta debe ser >= 1 y no permitir decimales

**Comment by k31kur0n0** [comment]
@belluccifranco 
La Contraseña del certificado debe ir encriptada.
Una cds debe darse de alta con la empresa, y darse de baja de la misma manera.
Corregir las validacines de los campos requeridos a la hora de usar FE.
Cambiar el mensaje de nro de punto de venta "incorrecto" a "invalido".

**Comment by belluccifranco** [comment]
@k31kur0n0 
- Agregar un nuevo script para cambiar el numero de serie de las facturas de ventas a 0
- Nuevo script para agregar los nuevos campos de factura electronica en las entidades: Factura, ConfiguracionDelSistema

**Comment by belluccifranco** [comment]
@k31kur0n0 
1- Quitar escriptacion del password del certificado
2- En el reporte de Factura:
      a- Cambiar el label "Ing. Brutos" por "Ingresos Brutos"
      b- Remplazar el nro de factura con los nuevos campos numSerieAfip y numFacturaAfip
      c- Cuando numSerieAfip y numFacturaAfip lleguen 0, no mostrarlos
      d- La regla b y c anteriores SOLO se aplican para facturas A, B, C. Pedido, Presupuesto, X e Y deben continuar usando los campos numFactura y numSerie
3- Modificar el script que agrega los campos nuevos a la estructura para que agregue tambien los dos nuevos campos de factura: numSerieAfip y numFacturaAfip
4- Agregar los nuevos campos numSerieAfip y numFacturaAfip al FINAL del listado de facturas de venta

**Comment by belluccifranco** [comment]
En el listado de facturas de venta, mover la columna Vencimiento CAE al final
