### ISSUE TITLE
Hotkeys que no funcionan en Punto De Venta.

### ISSUE THREAD

**Issue by k31kur0n0** [belluccifranco/sic#48]
En Punto de Venta, cuando el foco está sobre los campos de fecha, no funcionan los hotkeys.

Los Listeners están presentes.

**Comment by belluccifranco** [comment]
Estuve investigando un poco y al parecer el componente com.toedter.calendar.JDateChooser no dispara eventos de teclas, por ende el listener nunca recibe un evento para actuar con las hotkeys.

Se actualizó a la ultima version 1.4 pero el problema persiste.

No encontré nada en la documentación del autor.
