### ISSUE TITLE
Nuevos criterio de busqueda para Facturas de Venta y paginado.

### ISSUE THREAD

**Issue by k31kur0n0** [belluccifranco/sic#52]
Se debe agregar la posibilidad de buscar solo las facturas pagadas, y poder paginar en cantidades predeterminadas la busqueda de las mismas.

**Comment by belluccifranco** [comment]
@k31kur0n0 quitar el fetch con renglones cuando lista las facturas, no es necesario ya que no muestra los renglones

**Comment by belluccifranco** [comment]
Merged!
