### ISSUE TITLE
Facturacion parcial de Pedido

### ISSUE THREAD

**Issue by belluccifranco** [belluccifranco/sic#75]
Al facturar parciales con mas de 2 productos, no toma en cuenta el resto faltante y cierra el pedido como totalmente facturado. Funciona bien con 1 solo producto.

**Comment by k31kur0n0** [comment]
Pasos que realicé y no pude reproducir el error.
Realicé un pedido con 4 productos, 10 de cada uno.
Facturé 10 de un producto, se cargaron los otros 3 faltantes correctamente.
Facturé otros 10 de otro producto, se cargaron los otros 2 correctamente.
Facturé 5 de 10, de uno de los dos faltantes. Se cargaron correctamente.
Facturé otros 5 del otro producto que aún tenía 10 en cantidad, se siguen cargando correctamente.
Facturé los 5 restantes de los dos productos que aún quedaban en pedido. El pedido se cerró correctamente.

Necesito más información para reproducir el error.
